### ISSUE TITLE
About the USB host

### ISSUE THREAD

**Issue by regymm** [machdyne/schoko#2]
Hi, the board looks interesting! 

I'm curious how does the USB host work? For the other USB port, it seems a USB device is implemented in FPGA fabric(as in the DFU repo), but I didn't find any explanation about the USB host. Is there any demo code or so here or on Litex?

**Comment by machdyne** [comment]
Hi. The USB host controller is also implemented in FPGA fabric.

There is a USB OHCI included in LiteX as [usb_ohci.py](https://github.com/enjoy-digital/litex/blob/master/litex/soc/cores/usb_ohci.py) that is [from SpinalHDL](https://spinalhdl.github.io/SpinalDoc-RTD/dev/SpinalHDL/Libraries/Com/usb_ohci.html).

You can see where it's used by Schoko [here](https://github.com/litex-hub/litex-boards/blob/master/litex_boards/targets/machdyne_schoko.py#L132).

USB host support is automatically enabled when building [linux-on-litex-riscv](https://github.com/litex-hub/linux-on-litex-vexriscv) for Schoko.

I've successfully tested a USB keyboard, USB ethernet and USB flash drives with Schoko from Linux.

There does seem to be some issues when using multiple devices through the USB hubs that I've tried. I haven't been able to debug that yet but hopefully it will be resolved eventually.

**Comment by regymm** [comment]
Thanks for your quick reply. It's amazing to see USB host works well on 2 wires.
